#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeisMedrashProgram.data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BeisMedrashProgram")]
	public partial class BeisMedrashDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_user(tbl_user instance);
    partial void Updatetbl_user(tbl_user instance);
    partial void Deletetbl_user(tbl_user instance);
    partial void Inserttbl_forgotten_password(tbl_forgotten_password instance);
    partial void Updatetbl_forgotten_password(tbl_forgotten_password instance);
    partial void Deletetbl_forgotten_password(tbl_forgotten_password instance);
    partial void Inserttbl_beis_medrash(tbl_beis_medrash instance);
    partial void Updatetbl_beis_medrash(tbl_beis_medrash instance);
    partial void Deletetbl_beis_medrash(tbl_beis_medrash instance);
    partial void Inserttbl_member(tbl_member instance);
    partial void Updatetbl_member(tbl_member instance);
    partial void Deletetbl_member(tbl_member instance);
    #endregion
		
		public BeisMedrashDBDataContext() : 
				base(global::BeisMedrashProgram.data.Properties.Settings.Default.BeisMedrashProgramConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public BeisMedrashDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BeisMedrashDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BeisMedrashDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BeisMedrashDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_user> tbl_users
		{
			get
			{
				return this.GetTable<tbl_user>();
			}
		}
		
		public System.Data.Linq.Table<tbl_forgotten_password> tbl_forgotten_passwords
		{
			get
			{
				return this.GetTable<tbl_forgotten_password>();
			}
		}
		
		public System.Data.Linq.Table<tbl_beis_medrash> tbl_beis_medrashes
		{
			get
			{
				return this.GetTable<tbl_beis_medrash>();
			}
		}
		
		public System.Data.Linq.Table<tbl_member> tbl_members
		{
			get
			{
				return this.GetTable<tbl_member>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_users")]
	public partial class tbl_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _Email;
		
		private string _PasswordHash;
		
		private string _PasswordSalt;
		
		private int _BeisMedrashId;
		
		private EntitySet<tbl_forgotten_password> _tbl_forgotten_passwords;
		
		private EntityRef<tbl_beis_medrash> _tbl_beis_medrash;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordHashChanging(string value);
    partial void OnPasswordHashChanged();
    partial void OnPasswordSaltChanging(string value);
    partial void OnPasswordSaltChanged();
    partial void OnBeisMedrashIdChanging(int value);
    partial void OnBeisMedrashIdChanged();
    #endregion
		
		public tbl_user()
		{
			this._tbl_forgotten_passwords = new EntitySet<tbl_forgotten_password>(new Action<tbl_forgotten_password>(this.attach_tbl_forgotten_passwords), new Action<tbl_forgotten_password>(this.detach_tbl_forgotten_passwords));
			this._tbl_beis_medrash = default(EntityRef<tbl_beis_medrash>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordHash", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string PasswordHash
		{
			get
			{
				return this._PasswordHash;
			}
			set
			{
				if ((this._PasswordHash != value))
				{
					this.OnPasswordHashChanging(value);
					this.SendPropertyChanging();
					this._PasswordHash = value;
					this.SendPropertyChanged("PasswordHash");
					this.OnPasswordHashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordSalt", DbType="VarChar(255)")]
		public string PasswordSalt
		{
			get
			{
				return this._PasswordSalt;
			}
			set
			{
				if ((this._PasswordSalt != value))
				{
					this.OnPasswordSaltChanging(value);
					this.SendPropertyChanging();
					this._PasswordSalt = value;
					this.SendPropertyChanged("PasswordSalt");
					this.OnPasswordSaltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeisMedrashId", DbType="Int NOT NULL")]
		public int BeisMedrashId
		{
			get
			{
				return this._BeisMedrashId;
			}
			set
			{
				if ((this._BeisMedrashId != value))
				{
					if (this._tbl_beis_medrash.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBeisMedrashIdChanging(value);
					this.SendPropertyChanging();
					this._BeisMedrashId = value;
					this.SendPropertyChanged("BeisMedrashId");
					this.OnBeisMedrashIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_user_tbl_forgotten_password", Storage="_tbl_forgotten_passwords", ThisKey="Id", OtherKey="UserId")]
		public EntitySet<tbl_forgotten_password> tbl_forgotten_passwords
		{
			get
			{
				return this._tbl_forgotten_passwords;
			}
			set
			{
				this._tbl_forgotten_passwords.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_beis_medrash_tbl_user", Storage="_tbl_beis_medrash", ThisKey="BeisMedrashId", OtherKey="Id", IsForeignKey=true)]
		public tbl_beis_medrash tbl_beis_medrash
		{
			get
			{
				return this._tbl_beis_medrash.Entity;
			}
			set
			{
				tbl_beis_medrash previousValue = this._tbl_beis_medrash.Entity;
				if (((previousValue != value) 
							|| (this._tbl_beis_medrash.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_beis_medrash.Entity = null;
						previousValue.tbl_users.Remove(this);
					}
					this._tbl_beis_medrash.Entity = value;
					if ((value != null))
					{
						value.tbl_users.Add(this);
						this._BeisMedrashId = value.Id;
					}
					else
					{
						this._BeisMedrashId = default(int);
					}
					this.SendPropertyChanged("tbl_beis_medrash");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_forgotten_passwords(tbl_forgotten_password entity)
		{
			this.SendPropertyChanging();
			entity.tbl_user = this;
		}
		
		private void detach_tbl_forgotten_passwords(tbl_forgotten_password entity)
		{
			this.SendPropertyChanging();
			entity.tbl_user = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_forgotten_passwords")]
	public partial class tbl_forgotten_password : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Token;
		
		private int _UserId;
		
		private System.DateTime _TimeStamp;
		
		private EntityRef<tbl_user> _tbl_user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTokenChanging(string value);
    partial void OnTokenChanged();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnTimeStampChanging(System.DateTime value);
    partial void OnTimeStampChanged();
    #endregion
		
		public tbl_forgotten_password()
		{
			this._tbl_user = default(EntityRef<tbl_user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Token", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Token
		{
			get
			{
				return this._Token;
			}
			set
			{
				if ((this._Token != value))
				{
					this.OnTokenChanging(value);
					this.SendPropertyChanging();
					this._Token = value;
					this.SendPropertyChanged("Token");
					this.OnTokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					if (this._tbl_user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeStamp", DbType="DateTime NOT NULL")]
		public System.DateTime TimeStamp
		{
			get
			{
				return this._TimeStamp;
			}
			set
			{
				if ((this._TimeStamp != value))
				{
					this.OnTimeStampChanging(value);
					this.SendPropertyChanging();
					this._TimeStamp = value;
					this.SendPropertyChanged("TimeStamp");
					this.OnTimeStampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_user_tbl_forgotten_password", Storage="_tbl_user", ThisKey="UserId", OtherKey="Id", IsForeignKey=true)]
		public tbl_user tbl_user
		{
			get
			{
				return this._tbl_user.Entity;
			}
			set
			{
				tbl_user previousValue = this._tbl_user.Entity;
				if (((previousValue != value) 
							|| (this._tbl_user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_user.Entity = null;
						previousValue.tbl_forgotten_passwords.Remove(this);
					}
					this._tbl_user.Entity = value;
					if ((value != null))
					{
						value.tbl_forgotten_passwords.Add(this);
						this._UserId = value.Id;
					}
					else
					{
						this._UserId = default(int);
					}
					this.SendPropertyChanged("tbl_user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_beis_medrash")]
	public partial class tbl_beis_medrash : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _BeisMedrashName;
		
		private string _Logo;
		
		private string _Address;
		
		private string _City;
		
		private string _State;
		
		private string _Zip;
		
		private string _Phone;
		
		private int _BeisMedrashCode;
		
		private EntitySet<tbl_user> _tbl_users;
		
		private EntitySet<tbl_member> _tbl_members;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBeisMedrashNameChanging(string value);
    partial void OnBeisMedrashNameChanged();
    partial void OnLogoChanging(string value);
    partial void OnLogoChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipChanging(string value);
    partial void OnZipChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnBeisMedrashCodeChanging(int value);
    partial void OnBeisMedrashCodeChanged();
    #endregion
		
		public tbl_beis_medrash()
		{
			this._tbl_users = new EntitySet<tbl_user>(new Action<tbl_user>(this.attach_tbl_users), new Action<tbl_user>(this.detach_tbl_users));
			this._tbl_members = new EntitySet<tbl_member>(new Action<tbl_member>(this.attach_tbl_members), new Action<tbl_member>(this.detach_tbl_members));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeisMedrashName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string BeisMedrashName
		{
			get
			{
				return this._BeisMedrashName;
			}
			set
			{
				if ((this._BeisMedrashName != value))
				{
					this.OnBeisMedrashNameChanging(value);
					this.SendPropertyChanging();
					this._BeisMedrashName = value;
					this.SendPropertyChanged("BeisMedrashName");
					this.OnBeisMedrashNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logo", DbType="VarChar(50)")]
		public string Logo
		{
			get
			{
				return this._Logo;
			}
			set
			{
				if ((this._Logo != value))
				{
					this.OnLogoChanging(value);
					this.SendPropertyChanging();
					this._Logo = value;
					this.SendPropertyChanged("Logo");
					this.OnLogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(150)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(150)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(50)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="VarChar(50)")]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this.OnZipChanging(value);
					this.SendPropertyChanging();
					this._Zip = value;
					this.SendPropertyChanged("Zip");
					this.OnZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeisMedrashCode", DbType="Int NOT NULL")]
		public int BeisMedrashCode
		{
			get
			{
				return this._BeisMedrashCode;
			}
			set
			{
				if ((this._BeisMedrashCode != value))
				{
					this.OnBeisMedrashCodeChanging(value);
					this.SendPropertyChanging();
					this._BeisMedrashCode = value;
					this.SendPropertyChanged("BeisMedrashCode");
					this.OnBeisMedrashCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_beis_medrash_tbl_user", Storage="_tbl_users", ThisKey="Id", OtherKey="BeisMedrashId")]
		public EntitySet<tbl_user> tbl_users
		{
			get
			{
				return this._tbl_users;
			}
			set
			{
				this._tbl_users.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_beis_medrash_tbl_member", Storage="_tbl_members", ThisKey="Id", OtherKey="BeisMedrashId")]
		public EntitySet<tbl_member> tbl_members
		{
			get
			{
				return this._tbl_members;
			}
			set
			{
				this._tbl_members.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_users(tbl_user entity)
		{
			this.SendPropertyChanging();
			entity.tbl_beis_medrash = this;
		}
		
		private void detach_tbl_users(tbl_user entity)
		{
			this.SendPropertyChanging();
			entity.tbl_beis_medrash = null;
		}
		
		private void attach_tbl_members(tbl_member entity)
		{
			this.SendPropertyChanging();
			entity.tbl_beis_medrash = this;
		}
		
		private void detach_tbl_members(tbl_member entity)
		{
			this.SendPropertyChanging();
			entity.tbl_beis_medrash = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_members")]
	public partial class tbl_member : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MemberId;
		
		private string _EnTitle;
		
		private string _LastName;
		
		private string _FirstName;
		
		private string _HeTitle;
		
		private string _HeLastName;
		
		private string _HeFirstName;
		
		private string _HeSuffix;
		
		private string _AddStreet;
		
		private string _Apt;
		
		private string _City;
		
		private string _State;
		
		private string _Zip;
		
		private string _HomePhone;
		
		private string _CellPhone;
		
		private string _Email;
		
		private string _Notes;
		
		private string _Active;
		
		private string _SendEmail;
		
		private string _Type;
		
		private string _SendStatement;
		
		private System.Nullable<decimal> _TotalBalance;
		
		private System.Nullable<System.DateTime> _CreteDate;
		
		private System.Nullable<System.DateTime> _SyncTime;
		
		private int _BeisMedrashId;
		
		private EntityRef<tbl_beis_medrash> _tbl_beis_medrash;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMemberIdChanging(int value);
    partial void OnMemberIdChanged();
    partial void OnEnTitleChanging(string value);
    partial void OnEnTitleChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnHeTitleChanging(string value);
    partial void OnHeTitleChanged();
    partial void OnHeLastNameChanging(string value);
    partial void OnHeLastNameChanged();
    partial void OnHeFirstNameChanging(string value);
    partial void OnHeFirstNameChanged();
    partial void OnHeSuffixChanging(string value);
    partial void OnHeSuffixChanged();
    partial void OnAddStreetChanging(string value);
    partial void OnAddStreetChanged();
    partial void OnAptChanging(string value);
    partial void OnAptChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipChanging(string value);
    partial void OnZipChanged();
    partial void OnHomePhoneChanging(string value);
    partial void OnHomePhoneChanged();
    partial void OnCellPhoneChanging(string value);
    partial void OnCellPhoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnActiveChanging(string value);
    partial void OnActiveChanged();
    partial void OnSendEmailChanging(string value);
    partial void OnSendEmailChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnSendStatementChanging(string value);
    partial void OnSendStatementChanged();
    partial void OnTotalBalanceChanging(System.Nullable<decimal> value);
    partial void OnTotalBalanceChanged();
    partial void OnCreteDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreteDateChanged();
    partial void OnSyncTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnSyncTimeChanged();
    partial void OnBeisMedrashIdChanging(int value);
    partial void OnBeisMedrashIdChanged();
    #endregion
		
		public tbl_member()
		{
			this._tbl_beis_medrash = default(EntityRef<tbl_beis_medrash>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MemberId
		{
			get
			{
				return this._MemberId;
			}
			set
			{
				if ((this._MemberId != value))
				{
					this.OnMemberIdChanging(value);
					this.SendPropertyChanging();
					this._MemberId = value;
					this.SendPropertyChanged("MemberId");
					this.OnMemberIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnTitle", DbType="VarChar(150)")]
		public string EnTitle
		{
			get
			{
				return this._EnTitle;
			}
			set
			{
				if ((this._EnTitle != value))
				{
					this.OnEnTitleChanging(value);
					this.SendPropertyChanging();
					this._EnTitle = value;
					this.SendPropertyChanged("EnTitle");
					this.OnEnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(150)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(150)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeTitle", DbType="NVarChar(150)")]
		public string HeTitle
		{
			get
			{
				return this._HeTitle;
			}
			set
			{
				if ((this._HeTitle != value))
				{
					this.OnHeTitleChanging(value);
					this.SendPropertyChanging();
					this._HeTitle = value;
					this.SendPropertyChanged("HeTitle");
					this.OnHeTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeLastName", DbType="NVarChar(150)")]
		public string HeLastName
		{
			get
			{
				return this._HeLastName;
			}
			set
			{
				if ((this._HeLastName != value))
				{
					this.OnHeLastNameChanging(value);
					this.SendPropertyChanging();
					this._HeLastName = value;
					this.SendPropertyChanged("HeLastName");
					this.OnHeLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeFirstName", DbType="NVarChar(150)")]
		public string HeFirstName
		{
			get
			{
				return this._HeFirstName;
			}
			set
			{
				if ((this._HeFirstName != value))
				{
					this.OnHeFirstNameChanging(value);
					this.SendPropertyChanging();
					this._HeFirstName = value;
					this.SendPropertyChanged("HeFirstName");
					this.OnHeFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeSuffix", DbType="NVarChar(150)")]
		public string HeSuffix
		{
			get
			{
				return this._HeSuffix;
			}
			set
			{
				if ((this._HeSuffix != value))
				{
					this.OnHeSuffixChanging(value);
					this.SendPropertyChanging();
					this._HeSuffix = value;
					this.SendPropertyChanged("HeSuffix");
					this.OnHeSuffixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddStreet", DbType="VarChar(150)")]
		public string AddStreet
		{
			get
			{
				return this._AddStreet;
			}
			set
			{
				if ((this._AddStreet != value))
				{
					this.OnAddStreetChanging(value);
					this.SendPropertyChanging();
					this._AddStreet = value;
					this.SendPropertyChanged("AddStreet");
					this.OnAddStreetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apt", DbType="VarChar(50)")]
		public string Apt
		{
			get
			{
				return this._Apt;
			}
			set
			{
				if ((this._Apt != value))
				{
					this.OnAptChanging(value);
					this.SendPropertyChanging();
					this._Apt = value;
					this.SendPropertyChanged("Apt");
					this.OnAptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(50)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="VarChar(50)")]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this.OnZipChanging(value);
					this.SendPropertyChanging();
					this._Zip = value;
					this.SendPropertyChanged("Zip");
					this.OnZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomePhone", DbType="VarChar(50)")]
		public string HomePhone
		{
			get
			{
				return this._HomePhone;
			}
			set
			{
				if ((this._HomePhone != value))
				{
					this.OnHomePhoneChanging(value);
					this.SendPropertyChanging();
					this._HomePhone = value;
					this.SendPropertyChanged("HomePhone");
					this.OnHomePhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CellPhone", DbType="VarChar(50)")]
		public string CellPhone
		{
			get
			{
				return this._CellPhone;
			}
			set
			{
				if ((this._CellPhone != value))
				{
					this.OnCellPhoneChanging(value);
					this.SendPropertyChanging();
					this._CellPhone = value;
					this.SendPropertyChanged("CellPhone");
					this.OnCellPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(MAX)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="VarChar(50)")]
		public string Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendEmail", DbType="VarChar(50)")]
		public string SendEmail
		{
			get
			{
				return this._SendEmail;
			}
			set
			{
				if ((this._SendEmail != value))
				{
					this.OnSendEmailChanging(value);
					this.SendPropertyChanging();
					this._SendEmail = value;
					this.SendPropertyChanged("SendEmail");
					this.OnSendEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(50)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendStatement", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SendStatement
		{
			get
			{
				return this._SendStatement;
			}
			set
			{
				if ((this._SendStatement != value))
				{
					this.OnSendStatementChanging(value);
					this.SendPropertyChanging();
					this._SendStatement = value;
					this.SendPropertyChanged("SendStatement");
					this.OnSendStatementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalBalance", DbType="Money")]
		public System.Nullable<decimal> TotalBalance
		{
			get
			{
				return this._TotalBalance;
			}
			set
			{
				if ((this._TotalBalance != value))
				{
					this.OnTotalBalanceChanging(value);
					this.SendPropertyChanging();
					this._TotalBalance = value;
					this.SendPropertyChanged("TotalBalance");
					this.OnTotalBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreteDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreteDate
		{
			get
			{
				return this._CreteDate;
			}
			set
			{
				if ((this._CreteDate != value))
				{
					this.OnCreteDateChanging(value);
					this.SendPropertyChanging();
					this._CreteDate = value;
					this.SendPropertyChanged("CreteDate");
					this.OnCreteDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SyncTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> SyncTime
		{
			get
			{
				return this._SyncTime;
			}
			set
			{
				if ((this._SyncTime != value))
				{
					this.OnSyncTimeChanging(value);
					this.SendPropertyChanging();
					this._SyncTime = value;
					this.SendPropertyChanged("SyncTime");
					this.OnSyncTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeisMedrashId", DbType="Int NOT NULL")]
		public int BeisMedrashId
		{
			get
			{
				return this._BeisMedrashId;
			}
			set
			{
				if ((this._BeisMedrashId != value))
				{
					if (this._tbl_beis_medrash.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBeisMedrashIdChanging(value);
					this.SendPropertyChanging();
					this._BeisMedrashId = value;
					this.SendPropertyChanged("BeisMedrashId");
					this.OnBeisMedrashIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_beis_medrash_tbl_member", Storage="_tbl_beis_medrash", ThisKey="BeisMedrashId", OtherKey="Id", IsForeignKey=true)]
		public tbl_beis_medrash tbl_beis_medrash
		{
			get
			{
				return this._tbl_beis_medrash.Entity;
			}
			set
			{
				tbl_beis_medrash previousValue = this._tbl_beis_medrash.Entity;
				if (((previousValue != value) 
							|| (this._tbl_beis_medrash.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_beis_medrash.Entity = null;
						previousValue.tbl_members.Remove(this);
					}
					this._tbl_beis_medrash.Entity = value;
					if ((value != null))
					{
						value.tbl_members.Add(this);
						this._BeisMedrashId = value.Id;
					}
					else
					{
						this._BeisMedrashId = default(int);
					}
					this.SendPropertyChanged("tbl_beis_medrash");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
